const mongoose = require("mongoose");
const Card = require('./models/card');
const db = require('../../config/keys').mongoURI;


mongoose
  .connect(db, { useNewUrlParser: true })
  .then(() => console.log("Connected to MongoDB successfully"))
  .catch(err => console.log(err));

seedCards = [{left: "Bad",	right: "Good"},
{left: "Mildly addictive",	right: "Highly addictive"},
{left: "Hot",	right: "Cold"},
{left: "Normal",	right: "Weird"},
{left: "Colorless",	right: "Colorful"},
{left: "Low calorie",	right: "High calorie"},
{left: "Feels bad",	right: "Feels good"},
{left: "Inessential",	right: "Essential"},
{left: "Cheap",	right: "Expensive"},
{left: "Underrated weapon",	right: "Overrated weapon"},
{left: "Rare",	right: "Common"},
{left: "Unsexy emoji",	right: "Sexy emoji"},
{left: "Easy subject",	right: "Hard subject"},
{left: "Unknown",	right: "Famous"},
{left: "Difficult to use",	right: "Easy to use"},
{left: "Tired",	right: "Wired"},
{left: "Dirty",	right: "Clean"},
{left: "Requires luck",	right: "Requires skill"},
{left: "Flavorless",	right: "Flavorful"},
{left: "Boring topic",	right: "Fascinating topic"},
{left: "Bad actor",	right: "Good actor"},
{left: "Basic",	right: "Hipster"},
{left: "Dangerous job",	right: "Safe job"},
{left: "Fantasy",	right: "Sci-Fi"},
{left: "Casual",	right: "Formal"},
{left: "Underpaid",	right: "Overpaid"},
{left: "Dry",	right: "Wet"},
{left: "Underrated skill",	right: "Overrated skill"},
{left: "Forbidden",	right: "Encouraged"},
{left: "Sad song",	right: "Happy song"},
{left: "Fragile",	right: "Durable"},
{left: "Geek",	right: "Dork"},
{left: "Good",	right: "Evil"},
{left: "Worst day of the year",	right: "Best day of the year"},
{left: "Bad habit",	right: "Good habit"},
{left: "Cat person",	right: "Dog person"},
{left: "Guilty pleasure",	right: "Openly love"},
{left: "Untalented",	right: "Talented"},
{left: "Dark",	right: "Light"},
{left: "Underrated actor",	right: "Overrated actor"},
{left: "Hard to find",	right: "Easy to find"},
{left: "Ugly man",	right: "Beautiful man"},
{left: "Hard to remember",	right: "Easy to remember"},
{left: "Lowbrow",	right: "Highbrow"},
{left: "Unhealthy",	right: "Healthy"},
{left: "Bad man",	right: "Good man"},
{left: "Historically important",	right: "Historically irrelevant"},
{left: "Hairless",	right: "Hairy"},
{left: "Inflexible",	right: "Flexible"},
{left: "Normal pet",	right: "Exotic pet"},
{left: "Introvert",	right: "Extrovert"},
{left: "Book was better",	right: "Movie was better"},
{left: "Bad movie",	right: "Good movie"},
{left: "Ugly",	right: "Beautiful"},
{left: "Happens slowly",	right: "Happens suddenly"},
{left: "Job",	right: "Career"},
{left: "Loved",	right: "Hated"},
{left: "The Light Side of the Force",	right: "The Dark Side of the Force"},
{left: "Bad pizza topping",	right: "Good pizza topping"},
{left: "Dystopia",	right: "Utopia"},
{left: "Mature person",	right: "Immature person"},
{left: "Underrated thing to own",	right: "Overrated thing to own"},
{left: "Mean person",	right: "Nice person"},
{left: "Action movie",	right: "Adventure movie"},
{left: "Mental activity",	right: "Physical activity"},
{left: "Uncontroversial topic",	right: "Controversial topic"},
{left: "Need",	right: "Want"},
{left: "Dry food",	right: "Wet food"},
{left: "Normal thing to own",	right: "Weird thing to own"},
{left: "Straight",	right: "Curvy"},
{left: "Bad person",	right: "Good person"},
{left: "80s",	right: "90s"},
{left: "Ethical to eat",	right: "Unethical to eat"},
{left: "Movie",	right: "Film"},
{left: "Optional",	right: "Mandatory"},
{left: "Underrated letter of the alphabet",	right: "Overrated letter of the alphabet"},
{left: "Ordinary",	right: "Extraordinary"},
{left: "Hard to pronounce",	right: "Easy to pronounce"},
{left: "Low quality",	right: "High quality"},
{left: "Plain",	right: "Fancy"},
{left: "Has a bad reputation",	right: "Has a good reputation"},
{left: "Poorly made",	right: "Well made"},
{left: "Not a sandwich",	right: "A sandwich"},
{left: "Quiet place",	right: "Loud place"},
{left: "Comedy",	right: "Drama"},
{left: "Dangerous",	right: "Safe"},
{left: "Culturally significant",	right: "Culturally insignificant"},
{left: "Replaceable",	right: "Irreplaceable"},
{left: "Worst athlete of all time",	right: "Greatest athlete of all time"},
{left: "Role model",	right: "Bad influence"},
{left: "Useless major",	right: "Useful major"},
{left: "Peaceful",	right: "Warlike"},
{left: "Underrated movie",	right: "Overrated movie"},
{left: "Rough",	right: "Smooth"},
{left: "Bad for you",	right: "Good for you"},
{left: "Round",	right: "Pointy"},
{left: "Proof that God exists",	right: "Proof that God doesn’t exist"},
{left: "Sad movie",	right: "Happy movie"},
{left: "Waste of time",	right: "Good use of time"},
{left: "Scary animal",	right: "Nice animal"},
{left: "Mainstream",	right: "Niche"},
{left: "Short lived",	right: "Long lived"},
{left: "Nobody does it",	right: "Everybody does it"},
{left: "Smells bad",	right: "Smells good"},
{left: "Star Wars",	right: "Star Trek"},
{left: "Snack",	right: "Meal"},
{left: "Least evil company",	right: "Most evil company"},
{left: "Soft",	right: "Hard"},
{left: "Sustenance",	right: "Haute cuisine"},
{left: "Square",	right: "Round"},
{left: "Better hot",	right: "Better cold"},
{left: "Stupid",	right: "Brilliant"},
{left: "Artisanal",	right: "Mass produced"},
{left: "Bad superpower",	right: "Good superpower"},
{left: "Ineffective",	right: "Effective"},
{left: "Unbelievable",	right: "Believable"},
{left: "Trashy",	right: "Classy"},
{left: "Temporary",	right: "Permanent"},
{left: "Looks like a person",	right: "Doesn't look like a person"},
{left: "Tastes bad",	right: "Tastes good"},
{left: "Sport",	right: "Game"},
{left: "Uncool",	right: "Cool"},
{left: "Worst living person",	right: "Greatest living person"},
{left: "Underrated",	right: "Overrated"},
{left: "Messy food",	right: "Clean food"},
{left: "Unethical",	right: "Ethical"},
{left: "Bad gift",	right: "Good gift"},
{left: "Unfashionable",	right: "Fashionable"},
{left: "Freedom fighter",	right: "Terrorist"},
{left: "Unforgiveable",	right: "Forgiveable"},
{left: "Failure",	right: "Masterpiece"},
{left: "Harmless",	right: "Harmful"},
{left: "Gryffindor",	right: "Slytherin"},
{left: "Unhygienic",	right: "Hygienic"},
{left: "Bad music",	right: "Good music"},
{left: "Useless",	right: "Useful"},
{left: "Movie that Godzilla would ruin",	right: "Movie that Godzilla would improve"},
{left: "Unimportant",	right: "Important"},
{left: "Easy to spell",	right: "Hard to spell"},
{left: "Vice",	right: "Virtue"},
{left: "Underrated musician",	right: "Overrated musician"},
{left: "Unpopular activity",	right: "Popular activity"},
{left: "Divided",	right: "Whole"},
{left: "Unreliable",	right: "Reliable"},
{left: "Easy to kill",	right: "Hard to kill"},
{left: "Unstable",	right: "Stable"},
{left: "Round animal",	right: "Pointy animal"},
{left: "Bad TV show",	right: "Good TV show"},
{left: "Traditionally masculine",	right: "Traditionally feminine"},
{left: "Useless body part",	right: "Useful body part"},
{left: "Fad",	right: "Classic"},
{left: "Weak",	right: "Strong"},
{left: "Disgusting cereal",	right: "Delicious cereal"},
{left: "Useless invention",	right: "Useful invention"},
{left: "Liberal",	right: "Conservative"},
{left: "Unpopular",	right: "Popular"},
{left: "Friend",	right: "Enemy"},
{left: "Boring",	right: "Exciting"},
{left: "Smelly in a bad way",	right: "Smelly in a good way"},
{left: "Villain",	right: "Hero"},
{left: "Underrated thing to do",	right: "Overrated thing to do"},
{left: "Useless in an emergency",	right: "Useful in an emergency"},
{left: "For kids",	right: "For adults"},
{left: "Wise",	right: "Intelligent"},
{left: "Easy to do",	right: "Hard to do"},
{left: "Worthless",	right: "Priceless"},
{left: "Nature",	right: "Nurture"},
{left: "Dictatorship",	right: "Democracy"},
{left: "Normal greeting",	right: "Weird greeting"},
{left: "Dog name",	right: "Cat name"},
{left: "Non-partisan",	right: "Partisan"},
{left: "Limited",	right: "Infinite"},
{left: "Casual event",	right: "Formal event"},
{left: "Bad investment",	right: "Good investment"},
{left: "Small talk",	right: "Heavy topic"},
{left: "Mild",	right: "Spicy"},
{left: "Religious",	right: "Sacrilegious"},
{left: "Not art",	right: "Art"},
{left: "Illegal",	right: "Prohibited"},
{left: "Popular",	right: "Elitist"},
{left: "Out of control",	right: "In control"},
{left: "Quiet",	right: "Loud"},
{left: "Secret",	right: "Public knowledge"},
{left: "Too small",	right: "Too big"},
{left: "Short",	right: "Long"},
{left: "Worst year in history",	right: "Best year in history"},
{left: "Socialist",	right: "Capitalist"},
{left: "Little known fact",	right: "Well known fact"},
{left: "Stationary",	right: "Mobile"},
{left: "Local issue",	right: "Global issue"},
{left: "Talent",	right: "Skill"},
{left: "Worst era to time travel",	right: "Best era to time travel"},
{left: "The worst",	right: "The best"},
{left: "Small number",	right: "Large number"},
{left: "Old fashioned",	right: "Avant garde"},
{left: "Ugly word",	right: "Beautiful word"},
{left: "Small",	right: "Tiny"},
{left: "Unnatural",	right: "Natural"},
{left: "Genuine person",	right: "Phony person"},
{left: "Derivative",	right: "Original"},
{left: "Etiquette",	right: "Manners"},
{left: "Benefits you",	right: "Benefits everyone"},
{left: "Powerless",	right: "Powerful"},
{left: "Fruit",	right: "Vegetable"},
{left: "Science",	right: "Pseudoscience"},
{left: "Funny topic",	right: "Serious topic"},
{left: "Limp",	right: "Firm"},
{left: "Guilty pleasure",	right: "Actually just bad"},
{left: "Gossip",	right: "News"},
{left: "Hard to sit on",	right: "Easy to sit on"},
{left: "Not enough",	right: "Too much"},
{left: "Horizontal",	right: "Vertical"},
{left: "Unscented",	right: "Scented"},
{left: "Huggable",	right: "Not huggable"},
{left: "Heterogeneous",	right: "Homogenous"},
{left: "Inclusive",	right: "Exclusive"},
{left: "Bad dog breed",	right: "Good dog breed"},
{left: "Art",	right: "Commerce"},
{left: "One hit wonder",	right: "Pop icon"},
{left: "Bad advice",	right: "Good advice"},
{left: "Tick",	right: "Tock"},
{left: "Bad candy",	right: "Good candy"},
{left: "Traditional",	right: "Radical"},
{left: "Bad mouthfeel",	right: "Good mouthfeel"},
{left: "Illegal",	right: "Legal"},
{left: "Deep thought",	right: "Shallow thought"},
{left: "Bad school",	right: "Good school"},
{left: "Never on time",	right: "Always on time"},
{left: "Won't live to 100",	right: "Will live to 100"},
{left: "Bad Disney character",	right: "Good Disney character"},
{left: "Similar",	right: "Identical"},
{left: "Bad president",	right: "Good president"},
{left: "Weird",	right: "Strange"},
{left: "Famous",	right: "Infamous"},
{left: "Least powerful god",	right: "Most powerful god"},
{left: "Boring person",	right: "Fun person"},
{left: "Underrated book",	right: "Overrated book"},
{left: "Conventional wisdom",	right: "Fringe belief"},
{left: "Worst chore",	right: "Best chore"},
{left: "Endangered species",	right: "Overpopulated species"},
{left: "Blue",	right: "Green"},
{left: "Thrilling",	right: "Terrifying"},
{left: "Nerd",	right: "Jock"},
{left: "Expected",	right: "Unexpected"},
{left: "Unreasonable phobia",	right: "Reasonable phobia"},
{left: "Underrated game",	right: "Overrated game"}]

const seedDB = async () => {
  await Card.deleteMany({});
  await Card.insertMany(seedCards);
};

seedDB().then(() => {
  mongoose.connection.close();
});